src/cp/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from cp import views as cp_views

################################################################################


urlpatterns = patterns('cp.views',
    url(r'^$', login_required(cp_views.IndexView.as_view()), name="index"),

    url(r'^select-customer/(?P<pk>\d+)/$',
        login_required(cp_views.SelectCustomerView.as_view()),
        name="select_customer"
    ),
    url(r'^toggle-deployedtest-enabled/(?P<pk>\d+)/$',
        login_required(cp_views.ToggleDeployedTestEnabledView.as_view()),
        name="toggle_deployedtest_enabled"
    ),
    url(r'^toggle-testsetup-enabled/(?P<pk>\d+)/$',
        login_required(cp_views.ToggleTestSetupEnabledView.as_view()),
        name="toggle_testsetup_enabled"
    ),
    url(r'^build-test-setup/(?P<pk>\d+)/$',
        login_required(cp_views.BuildTestSetupView.as_view()),
        name="build_test_setup"
    ),
    url(r'^generate-deployed-test/(?P<agent_pk>\d+)/$',
        login_required(cp_views.GenerateDeployedTestView.as_view()),
        name="generate_deployed_test"
    ),
     url(r'^push-deployed-test/(?P<agent_pk>\d+)/$',
        login_required(cp_views.PushDeployedTestView.as_view()),
        name="push_deployed_test"
    ),
    url(r'^push-deployed-test-status/(?P<agent_pk>\d+)/$',
        login_required(cp_views.PushDeployedTestStatusView.as_view()),
        name="push_deployed_test_status"
    ),
)

src/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
# from django.contrib.auth import urls as auth_urls

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include("accounts.urls")),
    url(r'', include("cp.urls", namespace="cp")),

)\
+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/base/models.py
from django.core import urlresolvers
from django.contrib.contenttypes.models import ContentType
from django.db import models

# TODO
# class BaseManager()
#     pass
#   method for is_deleted func.


class BaseModel(models.Model):
    dt_created = models.DateTimeField(auto_now_add=True, verbose_name="Date created")
    dt_changed = models.DateTimeField(auto_now=True, verbose_name="Date changed")
    is_deleted = models.BooleanField(default=False, verbose_name='Is deleted')

    # TODO
    # objects =

    class Meta:
        abstract = True

    def __str__(self):
        return "%s%s [%s]" % (
            "DEL " if self.is_deleted else "",
            self.get_str(),
            self.id,
        )

    def get_str(self):
        raise NotImplementedError()

    def get_admin_url(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (content_type.app_label, content_type.model), args=(self.id,))

src/cp/models.py
import os

from django.db import models
from jsonfield import JSONField

from base.fields import PositionField
from base.models import BaseModel
from . import errors

from django.conf import settings

################################################################################
################################################################################


class Customer(BaseModel):
    name = models.CharField(max_length=255, verbose_name='Name', unique=True)
    position = PositionField(verbose_name='Position')
    ico_filename = models.CharField(max_length=255, verbose_name='Icon filename', blank=True, null=True, help_text="will be searched in %s" % settings.ICO_URL)
    dashboard_url = models.CharField(max_length=255, blank=True, null=True)

    def get_str(self):
        return self.name

    class Meta:
        ordering = ("is_deleted", "position", )

    def get_agents_count(self, deleted=False):
        return self.agents.filter(is_deleted=deleted).count()
    get_agents_count.short_description = "Agents"

    def get_environments_count(self, deleted=False):
        return self.environments.filter(is_deleted=deleted).count()
    get_environments_count.short_description = "Environments"


################################################################################


class Environment(BaseModel):
    name = models.CharField(max_length=255, verbose_name='Name')
    customer = models.ForeignKey(Customer, related_name='environments', verbose_name='Customer')
    position = PositionField(verbose_name='Position', collection='customer')

    class Meta:
        unique_together = (("customer", "name"),)
        ordering = ("customer", "is_deleted", "position",)

    def get_str(self):
        return "%s - %s" % (self.customer.name, self.name)

    def get_apps_count(self, deleted=False):
        # return 4
        return self.apps.filter(is_deleted=deleted).count()
    get_apps_count.short_description = "Applications"


################################################################################


class App(BaseModel):
    customer = models.ForeignKey(Customer, related_name='apps', verbose_name='Customer')
    name = models.CharField(max_length=255, verbose_name='Name', help_text='Name and version')
    start_url = models.URLField(blank=True, default='', verbose_name='Start URL', help_text='Leave empty for desktop tests')
    variables = JSONField(verbose_name='Variables', blank=True)
    is_enabled = models.BooleanField(verbose_name='Enabled', default=True)

    class Meta:
        unique_together = (("customer", "name"),)
        ordering = ("customer", "is_deleted", )
        verbose_name = "Application"
        verbose_name_plural = "Applications"

    def get_str(self):
        return self.name

################################################################################

class AppSetup(BaseModel):
    environment = models.ForeignKey(Environment, related_name='apps', verbose_name='Environment')
    app = models.ForeignKey(App, related_name='appsetups', verbose_name='Application')
    position = PositionField(verbose_name='Position', collection='environment')
    variables = JSONField(verbose_name='Variables', blank=True)
    is_enabled = models.BooleanField(verbose_name='Enabled', default=True)

    class Meta:
        unique_together = (("environment", "app"),)
        ordering = ("environment", "is_deleted", "position", )
        verbose_name = "Application setup"
        verbose_name_plural = "Applications setup"

    def get_str(self):
        return "%s: %s" % (self.environment.name, self.app.name)

    def get_variables(self):
        # TODO maybe join together ??
        return self.variables or self.app.variables

    def get_testsetups_count(self, deleted=False):
        return self.testsetups.filter(is_deleted=deleted).count()
    get_testsetups_count.short_description = "Test Setups"


################################################################################


class Agent(BaseModel):
    name = models.CharField(max_length=255, verbose_name='Name')
    ip = models.IPAddressField()
    port = models.IntegerField(blank=True, null=True)
    hostname = models.CharField(max_length=255)
    user_name = models.CharField(max_length=255)
    uxm_path = models.CharField(max_length=255, help_text='unix format, use /cygdrive/c/uxm for Windows OS, don\'t use trailing slash!')
    platform = models.CharField(choices=settings.PLATFORM_CHOICES, default=settings.PLATFORM_DEFAULT, max_length=255)
    encryption_interface = models.CharField(max_length=255, blank="true", default="", help_text='unix format, default empty = "eth0", no need to change on fresh Win instalations, serves as computing backend for password encryption')

    customer = models.ForeignKey(Customer, related_name='agents', verbose_name='Customer')
    position = PositionField(verbose_name='Position', collection='customer')
    description = models.CharField(max_length=255, blank=True, null=True)

    lat = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)
    lon = models.DecimalField(max_digits=10, decimal_places=7, blank=True, null=True)
    country_code = models.CharField(max_length=64, help_text='ISO 3166-1', blank=True, null=True)

    def get_str(self):
        return self.name

    def get_deployedtests_count(self, deleted=False):
        return self.deployedtests.filter(is_deleted=deleted).count()
    get_deployedtests_count.short_description = "Deployed Tests"

    def get_outbox_agent_path(self):
        return os.path.abspath(os.path.join(
            settings.MEDIA_ROOT,
            "outbox",
            "agent_%s" % str(self.pk).zfill(6)
        ))

    def get_log_file_name(self):
        return os.path.abspath(os.path.join(
            settings.DEPLOY_TEST_PATH, "agent_%s.log" % self.pk
        ))

    def get_os_path(self):
        if self.platform in settings.PLATFORM_WINDOWS:
            return self.uxm_path.replace("/cygdrive/c", "c:").replace("/", "\\")
        else:
            return self.uxm_path

    def get_destination_uri(self):
        return "%(user_name)s@%(ip)s:%(uxm_path)s" % self.__dict__


################################################################################


class Test(BaseModel):
    app = models.ForeignKey(App, verbose_name='Application', related_name='tests')
    name = models.CharField(max_length=255, verbose_name='Name')
    threshold_warn = models.IntegerField(verbose_name='WARN', blank=True, null=True)
    threshold_crit = models.IntegerField(verbose_name='CRIT', blank=True, null=True)
    is_uploaded = models.BooleanField(default=False)
    appsetups = models.ManyToManyField(AppSetup, through='TestSetup',
        # TODO: through_fields
        )

    TEST_SCRIPT_NAME = "test.js"

    #######################################

    class Meta:
        ordering = ("is_deleted", "name", )

    @classmethod
    def validate_data(cls, path):
        """otestuje/zvaliduje adresar s testem"""

        if cls.TEST_SCRIPT_NAME not in os.listdir(path):
            raise errors.InvalidTestError("Selected directory does not contain file %s" %  cls.TEST_SCRIPT_NAME)

        # TODO others checks

        return True

    def get_str(self):
        return self.name

    def get_testsetups_count(self, deleted=False):
        return self.testsetups.filter(is_deleted=deleted).count()
    get_testsetups_count.short_description = "Test Setups"

    def get_test_source_directory_name(self):
        return "test_id_%s" % str(self.pk).zfill(6)

    def get_test_source_directory_path(self):
        return os.path.join(
            settings.MEDIA_ROOT,
            "source",
            self.get_test_source_directory_name()
        )

    def upload_data(self, path):
        """presune a prejmenuje adresar s testem"""
        pass


################################################################################


class TestSetup(BaseModel):
    test = models.ForeignKey(Test, related_name='testsetups', verbose_name='Test')
    appsetup = models.ForeignKey(AppSetup, related_name='testsetups', verbose_name='AppSetup')
    threshold_warn = models.IntegerField(verbose_name='WARN', blank=True, null=True)
    threshold_crit = models.IntegerField(verbose_name='CRIT', blank=True, null=True)
    is_enabled = models.BooleanField(verbose_name='Enabled', default=True)

    build_fingerprint = models.CharField(max_length=255, null=True, blank=True)
    build_dt = models.DateTimeField(null=True, blank=True)

    def get_str(self):
        return "%s - %s - %s" % (
            self.appsetup.environment,
            self.appsetup,
            self.test
        )

    def is_builded(self):
        return os.path.exists(self.get_build_directory_path())

    def get_deployedtests_count(self, deleted=False):
        return self.deployedtests.filter(is_deleted=deleted).count()
    get_deployedtests_count.short_description = "Deployed Tests"

    def get_build_directory_name(self):
        # return "test_setup_%s" % str(self.pk).zfill(6)
        # due to logstash scope recognition
        return "%s^%s^%s^%s" % (self.appsetup.environment.customer.name, self.appsetup.environment.name, self.appsetup.app.name, self.test.name)

    def get_build_directory_path(self):
        return os.path.join(
            settings.MEDIA_ROOT,
            "build",
            self.get_build_directory_name()
        )


################################################################################


class DeployedTest(BaseModel):
    agent = models.ForeignKey(Agent, related_name='deployedtests', verbose_name='Agent')
    testsetup = models.ForeignKey(TestSetup, related_name='deployedtests', verbose_name='TestSetup')
    threshold_warn = models.IntegerField(verbose_name='WARN', blank=True, null=True)
    threshold_crit = models.IntegerField(verbose_name='CRIT', blank=True, null=True)
    is_enabled = models.BooleanField(verbose_name='Enabled', default=True)

    class Meta:
        unique_together = (

src/base/forms.py
from django import forms

class BaseModelForm(forms.ModelForm):
    pass

src/cp/forms.py
from django.forms import ValidationError
from base.forms import BaseModelForm

################################################################################

class TestSetupAdminForm(BaseModelForm):

    def clean(self):
        if self.cleaned_data["test"].app.pk != self.cleaned_data["appsetup"].app.pk:
            raise ValidationError(
                "Test and AppSetup is not compatible!",
                code="invalid"
            )
        return super(TestSetupAdminForm, self).clean()

################################################################################

class AppSetupAdminForm(BaseModelForm):

    def clean(self):
        if self.instance:
            if self.instance.testsetups.exclude(test__app=self.cleaned_data["app"]).exists():
                raise ValidationError(
                    "Exist TestSetup related to this AppSetup which is using another application (%(app)s)!",
                    params={"app": self.instance.app},
                    code="invalid"
                )
        return super(AppSetupAdminForm, self).clean()

src/base/views.py
# from django.conf import settings
# from django.contrib.auth.forms import AuthenticationForm
# from django.contrib.auth import login as auth_login, logout as auth_logout
# from django.http import HttpResponseRedirect
# from django.utils.decorators import method_decorator
# from django.views.decorators.debug import sensitive_post_parameters
# from django.views import FormView, View

# class Login(FormView):
#     form_class = AuthenticationForm

#     def form_valid(self, form):
#         redirect_to = settings.LOGIN_REDIRECT_URL
#         auth_login(self.request, form.get_user())
#         if self.request.session.test_cookie_worked():
#             self.request.session.delete_test_cookie()
#         return HttpResponseRedirect(redirect_to)

#     def form_invalid(self, form):
#         return self.render_to_response(self.get_context_data(form=form))

#     @method_decorator(sensitive_post_parameters('password'))
#     def dispatch(self, request, *args, **kwargs):
#         request.session.set_test_cookie()
#         return super(Login, self).dispatch(request, *args, **kwargs)

# class Logout(View):
#     def get(self, request, *args, **kwargs):
#         auth_logout(request)
#         return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)


# class LoginRequiredMixin(object):

#     @method_decorator(login_required)
#     def dispatch(self, *args, **kwargs):
#         return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


from django import http
import json

class JSONResponseMixin(object):
    # def render_to_response(self, context):
    #     "Returns a JSON response containing 'context' as payload"
    #     return self.get_json_response(self.convert_context_to_json(context))

    def json_response(self, context, **httpresponse_kwargs):
        "Construct an `HttpResponse` object."
        return http.HttpResponse(self.convert_context_to_json(context),
                                 content_type='application/json',
                                 **httpresponse_kwargs)

    def convert_context_to_json(self, context):
        "Convert the context dictionary into a JSON object"
        # Note: This is *EXTREMELY* naive; in reality, you'll need
        # to do much more complex handling to ensure that arbitrary
        # objects -- such as Django model instances or querysets
        # -- can be serialized as JSON.
        return json.dumps(context)

src/cp/templates/base.html
<!doctype html>{% load static from staticfiles  %}
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{% block title %}{% endblock %} | UXM</title>
        <link rel="stylesheet" href="{% static "css/foundation.css" %}" />
        <script src="{% static "js/vendor/modernizr.js" %}"></script>
    </head>
    <body>

        {% if request.user.is_authenticated %}
            <div class="row">
                {% include "menu.html" %}
                <ul class="breadcrumbs">
                    {% block breadcrumbs %}
                        <li><a href="{% url 'cp:index' %}">index</a></li>
                    {% endblock %}
                </ul>
            </div>
        {% endif %}

        <div class="row">
            {% block messages %}
                {% if messages %}
                    {% for message in messages %}
                        <div data-alert class="alert-box {{ message.tags }} radius">
                            {{ message }}
                            <a href="#" class="close">&times;</a>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endblock %}

            {% block content %}{% endblock %}
        </div>

        {% block endstatic %}
            <script src="{% static "js/vendor/jquery.js" %}"></script>
            <script src="{% static "js/foundation.min.js" %}"></script>
            <script>
                $(document).foundation();
            </script>
        {% endblock %}
    </body>
</html>

src/cp/templates/dashboard.html
{% extends "base.html" %}
{% load static from staticfiles  %}
{% load base %}

{% block title %}Index{% endblock %}

{% block endstatic %}
    {{ block.super }}
    <script type="text/javascript" async defer>
        jQuery(".js-confirm-toggle").on("click", function(e){
            var btn = jQuery(this);
            if (confirm("Realy?")){
                console.log(btn);
            } else {
                e.preventDefault();
            }
        });
    </script>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="large-12 columns">
            <h1>UXM dashboard</h1>
        </div>
    </div>

    <div class="row">
        <div class="large-12 columns">

            <table>
                {% for testsetup in testsetups %}

                    {% if forloop.first %}
                    <tr>
                        <td></td>
                        {% for agent in agents %}
                            <th>
                                <a href="{{ agent.get_admin_url }}">{{ agent.name }}</a> <small>{{ agent.get_platform_display }}</small>
                                <br />
                                <a href="{% url 'cp:push_deployed_test' agent.pk %}" class="label tiny">Deploy</a>
                                <!-- <a href="#" class="label tiny">Load</a> -->
                                <a href="{% url 'cp:generate_deployed_test' agent.pk %}" class="label tiny">Generate</a>
                            </th>
                        {% endfor %}
                    {% endif %}
                    </tr>

                    {% ifchanged testsetup.appsetup.environment.name %}
                    <tr>
                        <td>
                        <em><a href="{{ testsetup.appsetup.environment.get_admin_url }}">{{ testsetup.appsetup.environment.name }}<a></em>
                        </td>
                    </tr>
                    {% endifchanged %}
                    {% ifchanged testsetup.appsetup.app.name %}
                    <tr>
                        <td>
                        &nbsp;&nbsp;<strong><a href="{{ testsetup.appsetup.app.get_admin_url }}">{{ testsetup.appsetup.app.name }}</a></strong>
                        </td>
                    </tr>
                    {% endifchanged %}

                    <tr>
                        <td>
                            &nbsp;&nbsp;&nbsp;&nbsp;<a href="{{ testsetup.test.get_admin_url }}">{{ testsetup.test.name }}</a>&nbsp;
                            <span class="right">
                                <a href="{% url 'cp:toggle_testsetup_enabled' testsetup.pk %}" class="js-confirm-toggle">

                                    {% if not testsetup.test.is_uploaded %}
                                        <span class="label warning" title="test source is not ready (not uploaded from inbox)">N/A</span>
                                    {% endif %}

                                    {% if testsetup.is_enabled %}
                                        <span class="label success">Enabled</span>
                                    {% else %}
                                        <span class="label alert">Disabled</span>
                                    {% endif %}
                                </a>
                                {% if testsetup.is_builded %}
                                    <span class="label tiny secondary" title="TestSetup was build.">build</span>
                                {% else %}
                                    <a href="{% url 'cp:build_test_setup' testsetup.pk %}" class="label tiny">build</a>
                                {% endif %}
                            </span>
                        </td>

                        {% for agent in agents %}
                            <td>
                                {% if testsetup.is_enabled %}
                                    {% get_from_dict matrix testsetup.pk agent.pk as deployedtest %}
                                    {% if deployedtest %}
                                        <a href="{% url 'cp:toggle_deployedtest_enabled' deployedtest.pk  %}" title="" class="js-confirm-toggle">
                                            {% if deployedtest.is_enabled %}
                                                <span class="label success">Enabled</span>
                                            {% else %}
                                                <span class="label alert">Disabled</span>
                                            {% endif %}
                                        </a>
                                    {% else %}
                                        <span class="label secondary">Not deployed</span>
                                    {% endif %}
                                {% else %}
                                    <span class="label secondary">&mdash;</span>
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>


                {% endfor %}
            </table>

        </div>
    </div>


{% endblock %}

src/cp/templates/menu.html
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class="name">
            <h1><a href="#">UXM</a></h1>
        </li>
    </ul>

    <section class="top-bar-section">
        <ul class="left">
            <li class="divider"></li>
            <li class="has-dropdown">
                <a href="#">{{ active_customer }}</a>
                <ul class="dropdown">
                    {% for customer in customers %}
                        <li{% ifequal active_customer.pk customer.pk %} class="active" {% endifequal %}>
                            <a href="{% url 'cp:select_customer' customer.pk %}?next={{ request.path }}">
                                {{ customer }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
            <li class="divider"></li>
        </ul>

        <ul class="right">
            <li>
                <a href="{% url "logout" %}">Logout</a>
            </li>
        </ul>
    </section>
</nav>

src/cp/templates/push.html
{% extends "base.html" %}
{% load static from staticfiles  %}
{% load base %}

{% block title %}Index{% endblock %}

{% block endstatic %}
    {{ block.super }}
    <script type="text/javascript" async defer>
        jQuery(".js-confirm-toggle").on("click", function(e){
            var btn = jQuery(this);
            if (confirm("Realy?")){
                console.log(btn);
            } else {
                e.preventDefault();
            }
        });

        var counter = 0;
        var max_heartbeat_call = 500;
        var terminal = jQuery(".js-terminal");

        function tail(){
            jQuery.getJSON(
                "{% url 'cp:push_deployed_test_status' agent.pk %}"
            )
            .done(
                function(json){
                    terminal.html(json["agent"] + "\n");
                    terminal.scrollTop(terminal.height);
                    if (!json["push_done"]){
                        heartbeat();
                    }
            })
            .fail(
                function(jqxhr, textStatus, error) {
                    terminal.html("Request Failed: " + textStatus + "\n");
            })
        }
        function heartbeat(){
            if (counter > max_heartbeat_call){
                terminal.html("Max count of requests exceeded!" + "\n");
            } else {
                setTimeout(tail, 1000)
                counter += 1;
            }
        };
        heartbeat();
    </script>

    <style type="text/css">
        .terminal-wrapper {
            height: 500px;
            overflow-y: scroll;
            padding: 10px;
        }
    </style>

{% endblock %}

{% block content %}
    <div class="panel terminal-wrapper">
        <pre class="js-terminal"></pre>
    </div>
{% endblock %}